server:
  port: 8080
spring:
  h2:
    console:
      settings:
        web-allow-others: true
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:h2:mem:todo-assignment
    username: sa
    password: sa

